### ISSUE TITLE
Gulp doesn't create dist/css/frontend folder

### ISSUE THREAD

**Issue by saltcod** [magnificode/WPMakeOutput#11]
Running gulp creates a flat list of files in /dist/css like the attached image, but we're trying to enqueue /dist/css/frontend/style{$min}.css. 
![2017-12-14 at 7 21 am](https://user-images.githubusercontent.com/105593/33988669-9890eb5e-e09f-11e7-81ab-930ca92ab007.png)

**Comment by magnificode** [comment]
@saltcod with this new structure, we're going to need to alter our `{$min}` function to be more of a conditional since the minified and non-minified files exist in two different folders. 

The non minified CSS files should exist in `/css/src/`. So an updated $min conditional might look like this:

```php
$debug = apply_filters( 'wptheme_script_debug', false );
$min   = $debug || defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG );

if ( $min ) {
	add_editor_style( "assets/css/frontend/editor-style.min.css" );
} else {
	add_editor_style( "dist/editor-style.css" );
}
```

We may be able to refine that, but that's the direction. Let me know your thoughts!
