### ISSUE TITLE
Why do we need an /assets/src folder?

### ISSUE THREAD

**Issue by saltcod** [magnificode/WPMakeOutput#12]
Per: https://github.com/magnificode/WPMakeOutput/commit/b9d39bc51a85d70a309346e884bfa1930fcc493e

Not sure I'm fully getting why this src folder is needed. Why wouldn't style.css and style.min.css just live in /dist/?   Do the files in /src/ get committed? Why?  I suspect there's something not clicking about this for me!

**Comment by timwright12** [comment]
Typically /src gets committing and /dist doesn't as /dist (should be added to the .gitignore) only contains processed files to be distributed.

**Comment by saltcod** [comment]
So the structure should look like this: 


src/
- style.css

dist/
- style.min.css 


Where one is for local and one is for production?   I see a style.css in the dist folder as well and find that a little confusing is all.

**Comment by timwright12** [comment]
I would stay that there should be a /dist/style.css for local workflow and it may be different from /src/style.css in that style.css isn't processed through postCSS/CSSnext so it may be loaded up with @import rules

**Comment by saltcod** [comment]
Screenshot attached for additional clarity on what I'm asking about here.

![2017-12-14 at 1 29 pm](https://user-images.githubusercontent.com/105593/34004625-f93adcd4-e0d2-11e7-9f40-3b162c84b5a3.png)

**Comment by timwright12** [comment]
+1

**Comment by magnificode** [comment]
I'll look into this further, but as it stands CSS Next / CSS Nano are two separate tasks. CSS Nano requires a CSS file to be consumed, and then minified but would error out on a non compile CSS Next file. So the flow currently is such that CSS Next gets compiled, writes out to unminified CSS, nano then takes that unminified CSS file and minifies it.

As it stands I believe that the non minified CSS file is also getting spit out into the dist folder, which it should not be.

I'll take a closer look here and make sure we're not outputting things we don't need.

**Comment by magnificode** [comment]
@saltcod I've pushed a branch (https://github.com/magnificode/WPMakeOutput/tree/fix/css-output) that removes the unminified CSS files from the `/dist/css/` folder.

The `style.css` file in the `/css/frontend/` folder acts as a controller to import all the other partials into it. CSS Next then goes in, imports the mentioned files, and compiles it to the unminified files seen in `/css/src/`. I'd like to keep these here so that we can troubleshoot if there are issues in the minified CSS files.

Let me know if there's any other concerns here. If this is looking better, I'll get this merged into master.
