### ISSUE TITLE
A discussion on OOP in Make

### ISSUE THREAD

**Issue by jonbellah** [magnificode/WPMakeOutput#6]
First, I'm a :bigfan: of going to Gulp/Webpack and pushing towards unlocking ES features out-of-the-box (where currently, we need to add transpiling ourselves on each project).

That said, one thing that stood out to me was the OOP approach to the base theme setup (the `Theme` class). I'm not a fan of this approach, as I believe it encourages a less-than-ideal paradigm, particularly in an instance where such an approach is not necessary: not all things are (or need to be) classes.

There are a lot of posts out there that go into more detail than I will here, but here are a few that cover my opinions on the subject:
- [What is wrong with object oriented programming?](http://www.yegor256.com/2016/08/15/what-is-wrong-object-oriented-programming.html)
- [All evidence points to OOP being bullshit](https://content.pivotal.io/blog/all-evidence-points-to-oop-being-bullshit)
- [HN Thread: Object Oriented Programming is Inherently Harmful](https://news.ycombinator.com/item?id=8676872)

My biggest gripe is covered in the second post: inheritance vs. composition. As our codebases grow with projects, inheritance becomes a genuine pain point. Composition affords us more discrete functionality and, thus, more testable software.

Interested in hearing thoughts/opinions from others, though.

**Comment by magnificode** [comment]
@timwright12 - Interested to hear your thoughts on this. If @jonbellah is still so inclined to chime in that would be awesome 😬 - but I think the gist of this issue is around how we're organizing things like the CSS partials into pre-defined buckets. Whereas in the articles Jon mentions, it may make sense for the project to define what is needed as far as structure.

Do we see a better way forward for folder structure in this sense? Or Jon, is this issue deeper than just simple folder naming?

**Comment by jonbellah** [comment]
This issue is more than just folder naming. I'm referring to the PHP classes, specifically the `Theme` class in `includes/Theme.php`. I believe it encourages an OOP approach where such an approach isn't quite necessary (again, referring back to inheritance vs. composition).

I think the CSS/JS structure is 👍 .

**Comment by timwright12** [comment]
I think wp-make should address items at a macro level and let micro decisions be made on a per-project basis. Macro items being things like: we're using Webpack (and a basic set of npm modules to get up and running), as well as groundwork for unit testing and basic folder structures.

The extent to micro issues we should tackle would be things that are official 10up standards that can be automated and double as teaching opportunities for more jr members of the team. An example being setting up an eslint file that adheres to 10up standards, but also teaches you how to write better ES6 code.

For the individual file structure under /assets, wp-make should certainly have a default, but it should be easily torn down if your project required something different (like component-based organization).

**Comment by chanceymathews** [comment]
As a backend developer I think what is in the `includes/` folder now is fine. It contains simple examples of the two most common styles: standalone functions (template-tags.php) and classes (Theme.php). Developers can build off either (or both) as they see fit.

I second Tim's thoughts that this is not an issue worth tackling. The vast majority of software is written OO style. Pushing otherwise would be a little, well, pushy. I think the examples already there are appropriate.

**Comment by magnificode** [comment]
Noted, thanks for the input @chanceymathews!

**Comment by moraleida** [comment]
Agreed with @timwright12 and @chanceymathews. There are as many reasons to write OO-style code as any other style. Presenting the options (with explanatory comments) is more than enough for this project.

**Comment by ryanwelcher** [comment]
Personally, I have worked on projects where everything was a class and other where there were no classes at all. I agree with the sentiment that we shouldn't try to dictate one approach over the other - both have their uses. What should be stressed is consistency in the code base regardless of the approach.

**Comment by timwright12** [comment]
Can we close this one out?

**Comment by magnificode** [comment]
Indeed we can! Leaving the structure loose for now so that devs can make their own choice on how to build on top of the theme 👍
