### ISSUE TITLE
Switch Theme.php to core.php

### ISSUE THREAD

**Issue by saltcod** [magnificode/WPMakeOutput#8]
I'd like to separate this hopefully super-focused discussion from the more broad one surrounding the use of OOP in this theme. 

We still use the current wp make setup with all of our projects and have really been happy with the structure of functions.php and core.php. 

In general:
**functions.php** — contains theme constants (stylesheet directory, template dir path, etc), does all the require-ing of other files. Example:  https://gist.github.com/saltcod/2b908cdab17e4223c32d187a1a63f79f

**core.php** — does all the enqueuing of scripts, setup of basic theme functions, etc Example: https://gist.github.com/saltcod/86cb7df171c2e7fce9f5894ffa9a7e01

The difference wouldn't be huge (I don't think?). 

Love to get your thoughts!

**Comment by magnificode** [comment]
Totally agree here sir, I think `core.php` is the general semantic name that is used in our existing themes. I'll get this pushed out to master ASAP

**Comment by saltcod** [comment]
I could take care of this one if you’d like? Up to you!

**Comment by magnificode** [comment]
@saltcod appreciate it man! After thinking through this a little more, it may make sense to bring in a BEE to see what their opinions are. I'm not sure what the latest and greatest is in their eyes, and I'd love to get their input as well. Gonna post this in the engineering room and see where we get.

**Comment by ryanwelcher** [comment]
I'd tend to agree with @saltcod. I would expect the functions.php file to define constants, require files and call setup() functions and core.php to handle the majority of the common php tasks that we do on all projects.

**Comment by magnificode** [comment]
@ryanwelcher do we have a boilerplate for how we like to do that? I'm happy to drop in whatever standards we've established on the backend. Or perhaps this is a good opportunity to define a standard. Something that, much like the new theme, can be overridden if necessary, but provides a good starting point for the majority of projects.

**Comment by magnificode** [comment]
Also, totally should have mentioned, but @saltcod linked to some lovely looking boilerplate **functions.php** and **core.php** files above. I'm happy to utilize that as the standard if it looks good to you. Otherwise, if you think this is a discussion worth having with the rest of the BEEs @ryanwelcher, I'd be eager to see what comes of that!

**Comment by moraleida** [comment]
I like the general principles outlined by @saltcod . I also like "core" because it doesn't convey the idea of "Front End" as much as Theme does, and much of what we do on that file is not FE-only.

As for the actual names of the files, to me it feels like capitalized forms (Theme.php or Core.php) are preferred because of projects that might be leveraging [PSR-4 Autoloading](http://www.php-fig.org/psr/psr-4/). Having anything inside the **includes** folder abide to this naming structure makes this possible from the start.

Whatever decision comes out of this, I think the best solution will be to offer thoughtful comments on the top of each generated file indicating why we setup files this way, and how the developer can make the most out of this engineering style: which other files to create, when to use functions vs core vs creating a new file.

**Comment by ryanwelcher** [comment]
@magnificode  - the examples that @saltcod provided are pretty spot on. There might be some things that can be pulled out from theme but I'd start there.

As for the Theme.php class, I think I have to disagree with @moraleida on the filename, [WP standards  ](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions)dictate that filenames should follow the format of class-(class-name).php. So in the case of the Theme class, the file name should be class-theme.php.

There is a larger discussion on whether OOP is something we should be advocating in #6 so I'l move my comments there but if this class is going to be part of the scaffold, we should move the actions out of the `__construct` method and into an `init` or `setup` method. Actions in the constructor are very awkward to Unit Test.

**Comment by saltcod** [comment]
Hey all. Thanks for the discussion! To be clear: I have no opinion on the other OOP discussion really. 

As for this potential core.php file, given that it's already namepace'd, I don't see any reason why we'd need to wrap this up in a class. 

Happy to do up a PR if we're feeling ok with the overall direction here as guided by the sample files above. 

Thanks all!

**Comment by ryanwelcher** [comment]
I tend to agree with @saltcod on the namespace being sufficient. The only issue there is if we're looking at running this code on PHP versions that don't support them. That would be an edge case at this point but probably doesn't need to be addressed in this project.

**Comment by saltcod** [comment]
Agreed yeah. My sample code is from the old wp make generator, so that's been in place for a long time. I don't think I've done a project here yet where we've had to pull out the namespaces.

**Comment by magnificode** [comment]
@saltcod a PR for this would be very much appreciate sir 😄 thank you!

**Comment by magnificode** [comment]
This has been handled by #23. @saltcod changed the `Theme.php` file to `core.php` for now. This can certainly be changed on a per-project basis if the BEE sees fit. Closing out for now!
